application: readertogplusfriends
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon\.png
  static_files: favicon.png
  upload: favicon\.png

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: .*
  script: main.py
